### PR TITLE
refactored leaflet-measure

### PR DESCRIPTION
**Pull request by JowieXiang**
sorted out *leaflet.measure* feature from *Transerve* PR #159

### CODE REVIEW

**Review by janbehrens — COMMENTED** [review]
Why is leaflet-measure not installed via npm?

**Review by janbehrens — CHANGES_REQUESTED** [review]
The measure tool does not work properly if you emulate a touch device. There is no obvious way to cancel the measurement or to clear drawings.

**Comment by JowieXiang** [comment]
> Why is leaflet-measure not installed via npm?

#165 uses the leaflet-measure npm package. The style now looks different. I've tested using touch screen simulator and it works fine. Let me know if there's any problem.

**Comment by janbehrens** [comment]
With the mesaure tool from npm the measurements are given in imperial units. Can it be changed to use the metric system?

Also, *if* we use the npm version, the one in `views/map/leafletMeasure` is obsolete...

**Comment by janbehrens** [comment]
The light green drawings are really hard to see with the background maps we currently have.

**Review by janbehrens — APPROVED** [review]

**Pull request merged**
